### PR TITLE
Update Turkish translation

### PR DESCRIPTION
**Pull request by Beryesa**
Fix little mistakes and bring it closer to the established translations by the GNOME and KDE Turkish teams for consistency.

### CODE REVIEW

**Comment by Beryesa** [comment]
I should note however that cosmic-library-home doesn't fit (Kitaplık Ana _Sayfası_)
resim

Should we call it just "Home" (Ana Sayfa) or just "Library" or are there any other plans about longer strings in the UI? :P

**Comment by wash2** [comment]
Just "Home" would be fine for now. It's a bit awkward to have long names for these buttons. Maybe the text could be made to wrap, and buttons all increase in size to match the largest button height.

**Comment by Beryesa** [comment]
Hey, just before merging that, I see a string is missing in https://github.com/pop-os/cosmic-applibrary/blob/d88d0ba4bc19c35db49e3f1c581e79cf391a28fe/src/app.rs#L1187
Should I make another PR for that, or can I extend this one? 
Kindly, @wash2

**Comment by Beryesa** [comment]
Something like `text(&fl!("add-group").as_str())` and adding that key to the files helps
resim

**Comment by Beryesa** [comment]
Thanks, that was fast!
Updated to include it as well.

**Review by wash2 — APPROVED** [review]

**Pull request merged**
